name: 'Queue Release'
description: 'Adds a commit to the release queue via PR'

inputs:
  github_token:
    description: 'GitHub token used for authentication'
    required: true
  sha:
    description: 'Commit SHA to be queued for release'
    required: true
  branch:
    description: 'Target branch for the release (beta or main)'
    required: true
outputs:
  queue_position:
    description: 'Position in queue'
    value: ${{ steps.process_queue.outputs.position }}
  estimated_time:
    description: 'Estimated time until release'
    value: ${{ steps.process_queue.outputs.estimated_time }}
  pr_number:
    description: 'Created PR number'
    value: ${{ steps.create_pr.outputs.pr_number }}

runs:
  using: 'composite'
  steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Debug Inputs
      shell: bash
      working-directory: .github/scripts
      run: cargo run --bin step-debug-inputs
      env:
        INPUT_SHA: ${{ inputs.sha }}
        INPUT_BRANCH: ${{ inputs.branch }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        RUST_LOG: info

    - id: setup_queue
      shell: bash
      working-directory: .github/scripts
      run: cargo run --bin step_setup_queue
      env:
        RUST_LOG: info

    - id: process_queue
      shell: bash
      working-directory: .github/scripts
      run: cargo run --bin step_process_queue
      env:
        INPUT_SHA: ${{ inputs.sha }}
        INPUT_BRANCH: ${{ inputs.branch }}
        RUST_LOG: info

    - id: create_pr
      shell: bash
      working-directory: .github/scripts
      run: |
        RUST_LOG=info \
        GITHUB_TOKEN="${{ inputs.github_token }}" \
        QUEUE_BRANCH="${{ steps.setup_queue.outputs.branch }}" \
        INPUT_BRANCH="${{ inputs.branch }}" \
        INPUT_SHA="${{ inputs.sha }}" \
        QUEUE_POSITION="${{ steps.process_queue.outputs.position }}" \
        QUEUE_REMAINING="${{ steps.process_queue.outputs.remaining }}" \
        QUEUE_ESTIMATED_TIME="${{ steps.process_queue.outputs.estimated_time }}" \
        cargo run --bin step_create_pr

    - name: Ensure PR has correct labels
      shell: bash
      run: |
        PR_NUMBER="${{ steps.create_pr.outputs.pr_number }}"
        if [ -n "$PR_NUMBER" ]; then
          echo "Adding release-queue label to PR #$PR_NUMBER"
          gh pr edit $PR_NUMBER --add-label "release-queue"
        else
          echo "No PR number found in output"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
