name: 'DockerHub Build'
description: 'Builds and pushes Docker images to DockerHub'

inputs:
  environment:
    description: 'Target environment'
    required: true
  base_image:
    description: 'Base image to use'
    required: true

outputs:
  image_changed:
    description: 'Whether image was changed'
    value: ${{ steps.build.outputs.changed }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Verify Base Image
      shell: bash
      run: |
        echo "ðŸ” Verifying base image exists: ${{ inputs.base_image }}"
        if ! docker manifest inspect cmoe640/dev-environment:${{ inputs.base_image }} > /dev/null 2>&1; then
          echo "::error::Required base image cmoe640/dev-environment:${{ inputs.base_image }} not found in registry"
          echo "This suggests the setup-docker action failed to prepare the image correctly."
          exit 1
        fi
        echo "âœ… Base image verified"

    - name: Build and Push
      id: build
      shell: bash
      run: |
        if [[ "${{ steps.check_base.outputs.build_from_source }}" == "true" ]]; then
          # Building from source branch
          SOURCE_BRANCH="${{ steps.check_base.outputs.source_branch }}"
          echo "ðŸ—ï¸ Building from branch: $SOURCE_BRANCH"
          
          # Ensure we have the latest source
          git fetch origin $SOURCE_BRANCH
          git checkout origin/$SOURCE_BRANCH -- distributions/dockerhub/
          
          # Build using the branch's Dockerfile
          echo "ðŸš€ Building image from $SOURCE_BRANCH branch Dockerfile"
          docker build \
            -t cmoe640/dev-environment:${{ inputs.base_image }} \
            -f distributions/dockerhub/Dockerfile \
            --build-arg BRANCH=$SOURCE_BRANCH \
            .
            
          # Push the new image
          echo "ðŸ“¤ Pushing image to registry"
          docker push cmoe640/dev-environment:${{ inputs.base_image }}
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "â© Using existing image"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Report Build Status
      shell: bash
      run: |
        echo "## ðŸ—ï¸ Docker Build Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Build Details" >> $GITHUB_STEP_SUMMARY
        echo "- Environment: \`${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- Image: \`cmoe640/dev-environment:${{ inputs.base_image }}\`" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ steps.build.outputs.changed }}" == "true" ]]; then
          echo "- Status: âœ¨ New image built and pushed" >> $GITHUB_STEP_SUMMARY
        else
          echo "- Status: â™»ï¸ Using existing image" >> $GITHUB_STEP_SUMMARY
        fi
