name: 'Version Determiner'
description: 'Determines the next version number with prefix support'

outputs:
  new_version:
    description: 'The next version number'
    value: ${{ steps.set_version.outputs.version }}
  is_beta:
    description: 'Whether this is a beta version'
    value: ${{ steps.set_version.outputs.is_beta }}

runs:
  using: 'composite'
  steps:
    - name: Get Latest Tag
      id: get_latest_tag
      shell: bash
      run: |
        # Get the latest tag, defaulting to beta-v0.0.1 if none exists
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "beta-v0.0.1")
        echo "Latest tag: $latest_tag"
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

    - name: Set Next Version
      id: set_version
      shell: bash
      run: |
        latest_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        
        # Function to increment version component
        increment_version() {
          local version=$1
          local position=$2  # proud=1, default=2, fix=3
          
          IFS='.' read -ra parts <<< "$version"
          parts[$((position-1))]=$((parts[$((position-1))]+1))
          
          # Reset subsequent numbers to 0
          for ((i=position; i<${#parts[@]}; i++)); do
            parts[$i]=0
          done
          
          echo "${parts[*]}" | tr ' ' '.'
        }
        
        # Extract the numeric version part, ignoring prefix
        extract_version() {
          local tag=$1
          if [[ $tag =~ (stable|beta)-v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "${BASH_REMATCH[2]}"
          elif [[ $tag =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "${BASH_REMATCH[1]}"
          else
            echo "0.0.1"  # Default if no match
          fi
        }

        if [[ "$current_branch" == "beta" || "${{ github.event.inputs.source_branch }}" == "beta" ]]; then
          # Beta release path
          numeric_version=$(extract_version "$latest_tag")
          
          if [[ $latest_tag =~ ^beta- ]]; then
            # Already a beta tag, increment fix version (c)
            version=$(increment_version "$numeric_version" 3)
            new_version="beta-v${version}"
          elif [[ $latest_tag =~ ^stable- ]]; then
            # Coming from stable, increment default version (b) for new features
            version=$(increment_version "$numeric_version" 2)
            new_version="beta-v${version}"
          else
            # Default to initial beta
            new_version="beta-v0.0.1"
          fi
          
          is_beta="true"
        elif [[ "$current_branch" == "main" || "${{ github.event.inputs.source_branch }}" == "main" ]]; then
          # Stable release path
          numeric_version=$(extract_version "$latest_tag")
          
          if [[ $latest_tag =~ ^beta- ]]; then
            # Promoting beta to stable (same version number)
            new_version="stable-v${numeric_version}"
          elif [[ $latest_tag =~ ^stable- ]]; then
            # Increment fix version (c) for stable-to-stable
            version=$(increment_version "$numeric_version" 3)
            new_version="stable-v${version}"
          else
            # Default stable
            new_version="stable-v0.0.1"
          fi
          
          is_beta="false"
        fi
        
        echo "New version: $new_version"
        echo "version=$new_version" >> $GITHUB_OUTPUT
        echo "is_beta=$is_beta" >> $GITHUB_OUTPUT
