name: 'Create GitHub Release'
description: 'Creates a GitHub release with optional signing and branch-specific version determination'

inputs:
  new_version:
    description: 'New version to release (if not using auto)'
    required: true
    default: 'develop-v0.0.1'
  is_beta:
    description: 'Whether the release is a beta version'
    required: true
    default: 'false'
  prerelease:
    description: 'Whether this is a prerelease'
    required: false
    default: 'false'
  release_sha:
    description: 'SHA to create the release from'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
  bot_gpg_private_key:
    description: 'GPG private key for signing'
    required: false
  bot_gpg_passphrase:
    description: 'Passphrase for GPG private key'
    required: false
  bot_email:
    description: 'Email for git config'
    required: true
  bot_name:
    description: 'Name for git config'
    required: true
  allow_unsigned:
    description: 'Allow unsigned tags if GPG signing fails'
    required: false
    default: 'true'
  generate_release_notes:
    description: 'Auto-generate release notes from PRs'
    required: false
    default: 'true'

outputs:
  release_url:
    description: 'URL of the created release'
    value: ${{ steps.create_release.outputs.release_url }}
  version:
    description: 'The final version used for the release'
    value: ${{ inputs.new_version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Determine Release Version
      shell: bash
      id: determine_version
      # Ensure we use the version coming in from determine_version job within workflow_create_release.yml
      run: |
        if [ "${{ inputs.new_version }}" != "develop-v0.0.1" ]; then
          echo "use_version=${{ inputs.new_version }}" >> $GITHUB_OUTPUT
        else
          # Cancel the workflow here since we're not using the auto versioning logic
          # Output that we're cancelling due to a misconfiguration or incorrect input
          echo "version=develop-v0.0.1" >> $GITHUB_OUTPUT
          echo "This action is configured to use a specific version and not auto-detect. Cancelling." >> $GITHUB_OUTPUT
          exit 1
        fi
    
    # Compile Rust scripts if needed
    - name: Ensure Rust scripts are compiled
      if: steps.check_release.outputs.release_exists != 'true'
      shell: bash
      run: |
        if [ ! -f "${{ github.workspace }}/.github/scripts/target/debug/step_create_release" ]; then
          cd ${{ github.workspace }}/.github/scripts
          cargo build
        fi

    # Setup Git signing using existing step_setup_gpg.rs script
    - name: Setup GPG and Git
      if: steps.check_release.outputs.release_exists != 'true'
      id: setup_git
      uses: ./setup-git-signing
      with:
        bot_email: ${{ inputs.bot_email }}
        bot_name: ${{ inputs.bot_name }}
        bot_gpg_private_key: ${{ inputs.bot_gpg_private_key }}
        bot_gpg_passphrase: ${{ inputs.bot_gpg_passphrase }}
        debug_mode: 'true'

    # Run the release creation script
    - name: Check if release exists and create if needed
      id: create_release
      shell: bash
      run: |
        # If the release exists, the script (or gh cli) will set a non-zero exit code (or we can test here)
        if gh release view "$new_version" &>/dev/null; then
          echo "Release for version $new_version already exists."
          exit 0
        else
          # Call our release creation script. This script is assumed to capture the full releasing process.
          echo "Creating release for version $new_version..."
          ${{ github.workspace }}/.github/scripts/target/debug/step_create_release
        fi
      env:
        use_version: ${{ inputs.new_version }}
        INPUT_RELEASE_SHA: ${{ inputs.release_sha }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_PRERELEASE: ${{ inputs.prerelease }}
        INPUT_DRAFT: ${{ inputs.draft }}
        INPUT_GENERATE_RELEASE_NOTES: ${{ inputs.generate_release_notes }}
        INPUT_ALLOW_UNSIGNED: ${{ inputs.allow_unsigned }}

    # Set final output
    - name: Set Version Output
      shell: bash
      run: |
        echo "Final release version: ${{ steps.determine_version.outputs.use_version }}"
        echo "version=${{ steps.determine_version.outputs.new_version}}" >> $GITHUB_OUTPUT