name: Create Release

on:
  # Manual trigger with branch protection
  workflow_dispatch:
    inputs:
      trigger_sha:
        description: 'SHA to release (optional)'
        required: false
        type: string
      source_branch:
        description: 'Branch (must be beta or main)'
        required: false
        type: string
        default: 'beta'
      force_process:
        description: 'Force queue processing'
        required: false
        type: boolean
        default: false
      allow_unsigned:
        description: 'Allow unsigned releases if signing fails'
        required: false
        type: boolean
        default: true
  # Weekly scheduled release processing - only on beta/main
  schedule:
    # Run every Saturday at 10:00 AM CST (16:00 UTC)
    - cron: '0 16 * * SAT'

# Add concurrency to prevent multiple releases running simultaneously
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  MAINTAINER_GITHUB: '@BA-CalderonMorales'
  INITIAL_VERSION: 'v0.1.0-beta.1'  # Updated to match Cargo.toml
  DOCKER_IMAGE: 'ba-calderonmorales/dev-environment'

# NOTE: For full details on our release process, please refer to RELEASE_SCHEDULE.md at the repository root.
# This file uses branch protection (beta/main) to trigger automations based on merges from develop.

jobs:
  #####################################################################
  # Branch Protection Check
  # ---------------------
  # Purpose: Ensures releases only run on beta/main branches
  #
  # Flow:
  # 1. Validates branch name
  # 2. Blocks unauthorized release attempts
  # 3. Sets release type for downstream jobs
  #####################################################################
  branch_check:
    runs-on: ubuntu-22.04
    outputs:
      branch: ${{ steps.action.outputs.branch }}
      allowed: ${{ steps.action.outputs.allowed }}
    steps:
      - uses: actions/checkout@v4
      - id: action
        uses: ./.github/actions/branch-check
        with:
          source_branch: ${{ github.event.inputs.source_branch }}
          github_ref: ${{ github.ref }}

  #####################################################################
  # Determine Version
  # -----------------
  # Purpose: Determines the next version for the release
  #
  # Flow:
  # 1. Gets the latest tag
  # 2. Parses the version components
  # 3. Increments the beta number
  # 4. Sets the new version
  #####################################################################
  determine_version:
    needs: branch_check
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_action.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - id: version_action
        uses: ./.github/actions/version-determiner

  #####################################################################
  # Validate GPG Keys
  # -----------------
  # Purpose: Validates GPG keys before attempting release
  #
  # Flow:
  # 1. Tests GPG key import
  # 2. Verifies signing capability
  # 3. Provides diagnostic information
  #####################################################################
  validate_gpg:
    needs: [branch_check, determine_version]
    runs-on: ubuntu-22.04
    outputs:
      signing_enabled: ${{ steps.test_gpg.outputs.signing_enabled }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Test GPG Configuration
        id: test_gpg
        uses: ./.github/actions/setup-git-signing
        with:
          bot_email: ${{ secrets.BOT_EMAIL || 'actions@github.com' }}
          bot_name: ${{ secrets.BOT_NAME || 'GitHub Actions' }}
          bot_gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          bot_gpg_passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          debug_mode: 'true'
      
      - name: Report GPG Status
        run: |
          if [[ "${{ steps.test_gpg.outputs.signing_enabled }}" == "true" ]]; then
            echo "✅ GPG signing is properly configured with key ID: ${{ steps.test_gpg.outputs.gpg_key_id }}"
          else
            echo "⚠️ GPG signing is not available. Releases will be created without signatures."
            echo "   Please check your BOT_GPG_PRIVATE_KEY and BOT_GPG_PASSPHRASE secrets."
          fi

  #####################################################################
  # Process Release Queue
  # -------------------
  # Purpose: Processes the release queue and prepares for release creation
  #
  # Flow:
  # 1. Gets next item from queue
  # 2. Verifies all prerequisites
  # 3. Sets up release parameters
  #####################################################################
  process_queue:
    needs: [branch_check, determine_version, validate_gpg]
    # Modified to always run for manual triggers on allowed branches
    if: |
      (github.event_name == 'workflow_dispatch' && needs.branch_check.outputs.allowed == 'true') || 
      (github.event_name == 'schedule' && needs.branch_check.outputs.allowed == 'true')
    runs-on: ubuntu-22.04
    outputs:
      sha: ${{ steps.action.outputs.sha }}
      branch: ${{ steps.action.outputs.branch }}
      can_proceed: ${{ steps.action.outputs.can_proceed }}
      version: ${{ steps.action.outputs.version }}
      prerelease: ${{ steps.action.outputs.prerelease }}
    steps:
      - uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      - id: action
        uses: ./.github/actions/process-release-queue-job
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_sha: ${{ github.event.inputs.trigger_sha }}
          source_branch: ${{ github.event.inputs.source_branch }}
          force_process: ${{ github.event.inputs.force_process }}
          is_scheduled: ${{ github.event_name == 'schedule' }}
          initial_version: ${{ env.INITIAL_VERSION }}

  #####################################################################
  # Create Release
  # -------------
  # Purpose: Creates the actual release if queue processing succeeded
  #
  # Flow:
  # 1. Creates GitHub release
  # 2. Updates Docker tags
  # 3. Updates documentation
  #####################################################################
  create_release:
    needs: [branch_check, determine_version, validate_gpg, process_queue]
    # Modified to always run for manual triggers on allowed branches
    if: |
      (github.event_name == 'workflow_dispatch' && needs.branch_check.outputs.allowed == 'true') ||
      (github.event_name == 'schedule' && needs.branch_check.outputs.allowed == 'true' && needs.process_queue.outputs.can_proceed == 'true')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure token has right permissions

      - name: Create VERSION file
        run: |
          echo "${{ needs.determine_version.outputs.new_version }}" > VERSION

      - name: Create Release
        uses: ./.github/actions/create-release
        with:
          version: ${{ needs.determine_version.outputs.new_version }}
          prerelease: ${{ needs.process_queue.outputs.prerelease || 'true' }}  # Default to prerelease for beta
          release_sha: ${{ needs.process_queue.outputs.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bot_gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          bot_gpg_passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          bot_email: ${{ secrets.BOT_EMAIL || 'actions@github.com' }}
          bot_name: ${{ secrets.BOT_NAME || 'GitHub Actions' }}
          allow_unsigned: ${{ github.event.inputs.allow_unsigned || 'true' }}
          generate_release_notes: 'true'

  #####################################################################
  # Handle Failure
  # -------------
  # Purpose: Handles any failures in the release process
  #####################################################################
  handle_failure:
    needs: [branch_check, process_queue, create_release]
    if: |
      always() &&
      (needs.branch_check.outputs.allowed == 'true' && failure())
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/handle-release-failure
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          maintainer: ${{ env.MAINTAINER_GITHUB }}
          sha: ${{ needs.process_queue.outputs.sha }}
          branch: ${{ needs.process_queue.outputs.branch }}

  #####################################################################
  # Notify Queue
  # -------------
  # Purpose: Notifies the status of the release queue
  #####################################################################
  notify_queue:
    needs: [process_queue, create_release]
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-queue
        with:
          can_proceed: ${{ needs.process_queue.outputs.can_proceed }}
          commit_sha: ${{ needs.process_queue.outputs.sha }}
          release_result: ${{ needs.create_release.result }}
          github_token: ${{ secrets.GITHUB_TOKEN }}